Rename a field in two test exceptions.
When using the new version of thrift-typescript where exceptions derive from `Error`, it's problematic to shadow `Error`'s `message` field. In this case the problem is that our message was optional and `Error`'s message is required, but I think it's good practice to avoid reusing `message` altogether.

Before this change the `prettier --write 'src/**/*.ts'` command was showing this error:
```
src/tests/generated/common/AuthException.ts:81:12 - error TS2416: Property 'message' in type 'AuthException' is not assignable to the same property in base type 'ErrorStructLike'.
  Type 'string | undefined' is not assignable to type 'string'.
    Type 'undefined' is not assignable to type 'string'.

81     public message?: string;
              ~~~~~~~

src/tests/generated/exceptions/InvalidResult.ts:81:12 - error TS2416: Property 'message' in type 'InvalidResult' is not assignable to the same property in base type 'ErrorStructLike'.
  Type 'string | undefined' is not assignable to type 'string'.
    Type 'undefined' is not assignable to type 'string'.

81     public message?: string;
              ~~~~~~~

Found 4 errors.
```